# French

[addon]

download_button = "Télécharger"

[web]

# On top of all pages.
header_help = "Aide"
header_community = "Communauté"

# Context: activation page after receiving the magic link via email.
activate_title = "Activation"
activate_pending = "Patientez…"
activate_success = "Validé"
activate_error = "Erreur"
activate_no_addon_found = "Est-ce que l'addon est installé? Nous ne le trouvons pas."
activate_no_method_found = "Pas de méthode trouvée."
activate_help_me = "J'ai besoin d'aide."

# Context: webpage to restore a purchase, which require the user to enter their email.
issue_title = "Réactiver votre achat"
issue_submit = "Envoyer"
issue_thank_you = "merci"
issue_enter_email = "Pour réactiver votre achat, saisissez votre l'email que vous avez utilisé pour votre achat:"
issue_email_sent = "Nous vous avons envoyé un email avec un lien pour ré-activer votre achat."
issue_or_digit = "Ou vous pouvez aussi saisire le code à 6 chiffres envoyé."

# Context: this page - https://downloadhelper.net/
landing_text1 = "Téléchargez toutes vidéos sur internet, facile, ça marche!"
landing_text2 = "Plus de 1000+ sites supportés"
landing_text3 = "Utilisé par plus de 7 millions d'utilisateurs"
landing_text4 = "4.5 étoiles sur les stores"
landing_install_for_google = "Installer pour Chrome"
landing_install_for_mozilla = "Installer pour Firefox"
landing_install_for_microsoft = "Installer pour Edge"
landing_feature1_title = "Téléchargement en HD à pleine vitesse"
landing_feature1_description = "Les videos sont téléchargées en haute définition, à vitesse maximum. On est fier d'etre l'outil de téléchargement le plus rapide."
landing_feature2_title = "Archiver vos videos"
landing_feature2_description = "Archiver vos videos favorites, ne perdez plus vos médias."
landing_feature3_title = "Support de contenu streamé"
landing_feature3_description = "Visualiser les Live Stream hors-ligne, plus besoin d'etre présent constament."
landing_feature4_title = "Téléchargement audio"
landing_feature4_description = "Convertissez n'import quel flux videos en contenu audio, en MP3s ou podcasts."

# Context: this is for a "buy a license" webpage.
premium_hero1 = "Payez une fois, utilisez pour toujours"
premium_hero2 = "License 'lifetime' Video DownloadHelper"
premium_hero3 = "Téléchargez toutes videos, sans limites."

# Context: the page that opens after the addon gets installed.
welcome_text = "Votre downloadeur de vidéo est prêt!"
welcome_pin_message = "Activez l'icone dans votre barre d'outils:"
